service: test-layers
frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  deploymentMethod: direct
  region: us-east-1
  timeout: 900

layers:
  py-dependencies:
    path: dependencies
    compatibleRuntimes:
      - python3.11
    description: "my dependencies"