service: test-layers-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  deploymentMethod: direct
  region: us-east-1
  timeout: 900
  
functions:
  hello:
    handler: hello.handler
    url: true
    layers:
      - "${cf:test-layers-${self:provider.stage}.NodeDashdependenciesLambdaLayerQualifiedArn}"